services:
  server:
#    build: .
    image: nginx
    restart: always
    ports:
      - 2280:80
    volumes:
      - /home/zx/gluster/nanopore.dna:/srv:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .htpasswd:/etc/nginx/.htpasswd:ro
